=== smartcommunitylab/sco.percorsi/sco.percorsi-web/XSD/datamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://xml.percorsi.smartcommunitylab.it"
           xmlns:tns="http://xml.percorsi.smartcommunitylab.it"
           elementFormDefault="qualified">

    <xs:element name="PathData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="path" minOccurs="1" maxOccurs="unbounded" type="tns:Path"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="i18nText">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="CustomAttribute">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Category">
        <xs:sequence>
            <xs:element name="name" type="tns:i18nText" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="description" type="tns:i18nText" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="image" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="categoryId" use="required"/>
    </xs:complexType>
    
    <xs:element name="Categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" type="tns:Category" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="lastChange" type="xs:dateTime" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="Multimedia">
        <xs:sequence>
            <xs:element name="title" type="tns:i18nText" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="url" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="userDefined" type="xs:boolean" use="optional" default="false"/>    
        <xs:attribute name="userId" type="xs:string" use="optional"/>    
    </xs:complexType>
    
    <xs:complexType name="Location">
        <xs:attribute name="latitude" type="xs:double" use="required"/>    
        <xs:attribute name="longitude" type="xs:double" use="required"/>    
    </xs:complexType>
    
    <xs:complexType name="POI">
        <xs:sequence>
            <xs:element name="title" type="tns:i18nText" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="description" type="tns:i18nText" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="image" type="tns:Multimedia" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="video" type="tns:Multimedia" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="audio" type="tns:Multimedia" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="externalURL" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
            <xs:element name="coordinates" type="tns:Location" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="poiId" type="xs:string" use="required"/>    
    </xs:complexType>
    
    <xs:complexType name="Path">
        <xs:sequence>
            <xs:element name="title" type="tns:i18nText" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="description" type="tns:i18nText" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="category" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="image" type="tns:Multimedia" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="video" type="tns:Multimedia" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="audio" type="tns:Multimedia" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="externalURL" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
            <xs:element name="attributes" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" type="tns:CustomAttribute" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="shape" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="poi" type="tns:POI" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="pathId" type="xs:string" use="required"/>    
    </xs:complexType>
    
</xs:schema>

=== smartcommunitylab/sco.percorsi/sco.percorsi-web/src/test/resources/categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Categories lastChange="2001-12-31T12:00:00" xmlns:tns="http://xml.percorsi.smartcommunitylab.it" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.percorsi.smartcommunitylab.it ../../../XSD/datamodel.xsd ">
  <tns:category categoryId="c1">
    <tns:name lang="it">Nome1</tns:name>
    <tns:name lang="en">Name1</tns:name>
    <tns:description lang="it">Descrizione1</tns:description>
    <tns:description lang="en">Description1</tns:description>
    <tns:image>http://tempuri.org</tns:image>
  </tns:category>
  <tns:category categoryId="c2">
    <tns:name lang="it">Nome2</tns:name>
    <tns:name lang="en">Name2</tns:name>
    <tns:description lang="it">Descrizione2</tns:description>
    <tns:description lang="en">Description2</tns:description>
    <tns:image>http://tempuri.org</tns:image>
  </tns:category>
</tns:Categories>

=== smartcommunitylab/sco.percorsi/sco.percorsi-web/src/test/resources/paths.xml
<?xml version="1.0" encoding="UTF-8"?>
<PathData xmlns="http://xml.percorsi.smartcommunitylab.it" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.percorsi.smartcommunitylab.it ../../../XSD/datamodel.xsd ">
  <path pathId="path1">
    <title lang="">title</title>
    <description lang="">description</description>
    <category>category1</category>
    <category>category2</category>
    <image>
      <url>http://tempuri.org</url>
    </image>
    <video>
      <url>http://tempuri.org</url>
    </video>
    <externalURL>http://tempuri.org</externalURL>
    <attributes>
      <attribute name="DURATION">240</attribute>
      <attribute name="LENGTH">5</attribute>
      <attribute name="DIFFICULTY">1</attribute>
    </attributes>
    <shape>shape</shape>
    <poi poiId="1">
      <title lang="">title-poi1</title>
      <description lang="">description</description>
      <image>
        <url>http://tempuri.org</url>
      </image>
      <video>
        <url>http://tempuri.org</url>
      </video>
      <audio>
        <url>http://tempuri.org</url>
      </audio>
      <coordinates latitude="0.0" longitude="0.0"/>
    </poi>
    <poi poiId="2">
      <title lang="">title-poi2</title>
      <description lang="">description</description>
      <image>
        <url>http://tempuri.org</url>
      </image>
      <video>
        <url>http://tempuri.org</url>
      </video>
      <audio>
        <url>http://tempuri.org</url>
      </audio>
      <coordinates latitude="0.0" longitude="0.0"/>
    </poi>
    </path>
</PathData>
